---
- name: Install httpd
  hosts: serverlist
  become: root

  tasks:
  - name: Install httpd
     yum:
      name: httpd
      state: latest
  - name: Create index.html file
    file: 
     name: /var/www/html/index.html
     state: touch
  - name: Add Content
    lineinfile:
     line: "Hello Atlanta"
     path: /var/www/html/index.html
  - name: Start httpd
    service:
     name: httpd 
     state: started
     
